// Chamonix-Mont-Blanc, France — a Haute-Savoie resort added to the catalog.
// Shape mirrors val-thorens.ts (see resorts/types.ts for the schema;
// resorts/shared.ts for reusable options like US_INSURANCE).

import type { Resort, SnowMonth } from './types';
import type { TripComponent } from '../tripBuilderData';
import { alpineWeeks } from '../seasonData';
import { US_INSURANCE } from './shared';

const components: TripComponent[] = [
  {
    id: 'flights',
    label: 'Getting there',
    icon: '✈️',
    defaultEnabled: true,
    defaultOptionId: 'flight-onestop',
    unitHint: 'Round trip per traveler — mixable per person',
    options: [
      {
        id: 'flight-onestop',
        name: 'JFK 1-stop economy (TAP / ITA)',
        tier: 'Budget',
        description:
          'JFK → GVA via Lisbon (TAP) or Rome (ITA), ~11–13 h door to door. Geneva is the closest gateway to the Chamonix valley (~88 km).',
        price: 620,
        currency: 'USD',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.google.com/travel/flights/flights-from-new-york-to-geneva.html',
        note: 'Verified 1-stop band $571–$710 round trip mid-2026 snapshots; Dec/Feb holiday weeks run toward $1,000+. International air is VAT-exempt.',
      },
      {
        id: 'flight-nonstop',
        name: 'SWISS nonstop JFK → GVA',
        tier: 'Premium',
        description:
          'Daily nonstop, ~7.5 h eastbound — the comfortable Saturday-changeover option. SWISS is the most frequent nonstop carrier to Geneva.',
        price: 780,
        currency: 'USD',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.kayak.com/flight-routes/New-York-John-F-Kennedy-Intl-JFK/Geneva-Geneve-Cointrin-GVA',
        note: 'Nonstop RT ~$706 observed; December peak averages ~$1,200.',
      },
      {
        id: 'flight-united',
        name: 'United / Delta nonstop JFK → GVA',
        tier: 'Premium',
        description: 'Seasonal daily nonstops on United and Delta, ~8 h — book early for holiday weeks.',
        price: 760,
        currency: 'USD',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.kayak.com/flight-routes/New-York-John-F-Kennedy-Intl-JFK/Geneva-Geneve-Cointrin-GVA',
        note: 'RT ~$707 observed off-peak; holiday weeks materially higher.',
      },
      {
        id: 'flight-eu',
        name: 'Intra-EU flight → Geneva',
        tier: 'From Europe',
        description:
          'Short-haul round trip to GVA from a European city (LHR/AMS/BER/MAD class of routes) for group members already in Europe.',
        price: 165,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.google.com/travel/flights?q=flights%20to%20GVA',
        note: 'Typical €80–250 round trip booked ahead; EasyJet/BA/KLM/Lufthansa. Quoted fares are final.',
      },
    ],
  },
  {
    id: 'hotel',
    label: 'Accommodation — 7 nights',
    icon: '🏨',
    defaultEnabled: true,
    defaultOptionId: 'hotel-morgane',
    unitHint: 'Half board unless noted',
    options: [
      {
        id: 'hotel-rockypop',
        lat: 45.8974,
        lon: 6.8153,
        name: 'RockyPop Chamonix ★★★ (Les Houches)',
        tier: 'Budget',
        description:
          'Colourful affordable design hotel at the valley entrance in Les Houches — modular rooms sleeping 2–12, restaurant, bar and free shuttle links.',
        price: 100,
        currency: 'EUR',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.10,
        url: 'https://www.rockypop.com/en/chamonix/',
        contact: 'reception.chamonix@rockypop.com · +33 4 85 30 00 00',
        imageUrl: 'https://www.rockypop.com/app/uploads/2025/07/rockypop-chamonix-dormir-1.webp',
        note: 'RockyDuo room B&B ~€90–130/room/night; engine-priced. Les Houches is a 15-min drive from central Chamonix.',
      },
      {
        id: 'hotel-morgane',
        lat: 45.9199,
        lon: 6.8686,
        name: 'Hôtel Le Morgane ★★★★',
        tier: 'Mid',
        description:
          'Boutique wellness 4★ in central Chamonix, 100 m from the Aiguille du Midi cable car — 56 rooms, indoor pool and spa.',
        price: 145,
        currency: 'EUR',
        unit: 'per_person_night',
        vatRate: 0.10,
        url: 'https://morgane-hotel-chamonix.com/en/',
        contact: 'reservation@hotelmorganechamonix.com · +33 4 50 53 57 15',
        imageUrl: 'https://morgane-hotel-chamonix.com/assets/themes/apiandyou//public/images/hotel-morgane-chamonix.png',
        note: 'Official "Snow Package" half-board €117–157 pp/night. Dynamic pricing — check engine.',
      },
      {
        id: 'hotel-grandalpes',
        lat: 45.9236,
        lon: 6.8697,
        name: 'Grand Hôtel des Alpes ★★★★★',
        tier: 'Premium',
        description:
          'Restored 1840 belle-époque 5★ in the heart of Chamonix on rue du Docteur Paccard — classic Alpine rooms, spa and pool.',
        price: 280,
        currency: 'EUR',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.10,
        url: 'https://grandhoteldesalpes.com/en/',
        contact: 'info@grandhoteldesalpes.com · +33 4 50 55 37 80',
        imageUrl: 'https://grandhoteldesalpes.com/wp-content/uploads/2020/03/MB_1888-chambre-classique-e1584112526656.jpg',
        note: 'Classic double €220–350/room/night; suites €475–950. City tax €3.60 pp/night; parking €25/day.',
      },
      {
        id: 'hotel-albert1er',
        lat: 45.9265,
        lon: 6.8677,
        name: 'Le Hameau Albert 1er ★★★★★ (Relais & Châteaux)',
        tier: 'Luxury',
        description:
          'The Carrier family flagship 5★ Relais & Châteaux with a 1-Michelin-star restaurant, old-wood chalets, gardens, indoor/outdoor pool and spa — Chamonix’s premier luxury address.',
        price: 300,
        currency: 'EUR',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.10,
        url: 'https://www.hameaualbert.fr/en',
        contact: 'infos@hameaualbert.fr · +33 4 50 53 05 09',
        imageUrl: 'https://www.hameaualbert.fr/sites/default/files/2022-08/intro.jpg',
        note: 'From ~€300/double/night room-only; suites/chalets higher, half-board as a supplement. Position approximate.',
      },
      {
        id: 'hotel-odalys-isatis',
        lat: 45.9155,
        lon: 6.8618,
        name: 'Résidence Prestige Odalys Isatis ★★★★ (apartments)',
        tier: 'Apartment',
        description:
          '4★ self-catering residence near the town centre — 50 units with kitchenettes, indoor pool, sauna, spa and free parking. Self-catered.',
        price: 1100,
        currency: 'EUR',
        unit: 'per_unit_week',
        capacity: 4,
        vatRate: 0.10,
        url: 'https://www.odalys-vacation-rental.com/prestige-residences/',
        contact: 'Booking via Odalys / Chamonix tourist office · 25 chemin de Saint-Roch, 74400 Chamonix',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/92/ca/1e/caption.jpg?w=900&h=500&s=1',
        note: 'Winter 2–4-person apartment ~€900–1,400/week (nightly ~€109–524). Estimate for a 4-pax week — engine-priced. Position approximate.',
      },
    ],
  },
  {
    id: 'transfer',
    label: 'Airport transfer GVA ⇄ Chamonix',
    icon: '🚐',
    defaultEnabled: true,
    defaultOptionId: 'transfer-mountaindropoffs',
    unitHint: '88 km, ~1 h 15 each way',
    options: [
      {
        id: 'transfer-mountaindropoffs',
        name: 'Mountain Drop-offs shared shuttle',
        tier: 'Budget',
        description:
          'Door-to-door shared shuttle GVA → Chamonix, Chamonix-based operator running any day — the standard shared option for the short Geneva hop.',
        price: 82,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.10,
        url: 'https://www.mountaindropoffs.com/geneva-to-chamonix-transfer/',
        contact: '+33 4 50 47 17 73',
        note: '~€35–45 pp one-way → ~€70–90 pp round trip. Chamonix Valley Transfers and AlpyBus are comparable alternatives.',
      },
      {
        id: 'transfer-public',
        name: 'FlixBus / easyBus (public transport)',
        tier: 'Budget',
        description:
          'Scheduled coach GVA → Chamonix (~1 h 30–2 h) — the cheapest way up the valley. Runs any day; book seats and skis ahead.',
        price: 40,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.10,
        url: 'https://www.genevatourism.org/geneva-transportation-guide/geneva-to-chamonix/',
        contact: 'Book via flixbus.com / easybus.com',
        note: '~€10–25 pp one-way → ~€20–50 pp return. Cheapest option; less flexible than door-to-door.',
      },
      {
        id: 'transfer-train',
        name: 'Train via Martigny (Mont-Blanc Express)',
        tier: 'Budget',
        description:
          'Rail Geneva → Martigny (SBB), then the scenic Mont-Blanc Express through Vallorcine into Chamonix — no direct GVA rail, but the classic mountain-train arrival.',
        price: 75,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.10,
        url: 'https://www.sbb.ch/en',
        contact: 'SBB + TER/Mont-Blanc Express connections',
        note: '~€30–45 pp one-way → ~€60–90 pp return. Scenic but slower with changes.',
      },
      {
        id: 'transfer-cvt-private',
        name: 'Chamonix Valley Transfers private van (1–8 pax)',
        tier: 'Premium',
        description:
          'Door-to-door private van from Geneva, any day and any flight time — the option when the group wants one vehicle to the chalet door.',
        price: 500,
        currency: 'EUR',
        unit: 'per_vehicle_return',
        capacity: 8,
        vatRate: 0.10,
        url: 'https://www.chamonix-valley-transfers.co.uk/',
        contact: 'Via chamonix-valley-transfers.co.uk',
        note: 'From ~€250/van one-way → ~€500 return for up to 8. Quote-based; peak Saturdays top of band.',
      },
    ],
  },
  {
    id: 'skipass',
    label: 'Ski pass — 6 days',
    icon: '🎿',
    defaultEnabled: true,
    defaultOptionId: 'pass-mbu',
    unitHint: 'Chamonix valley — several separate areas',
    options: [
      {
        id: 'pass-mbu',
        name: '6-day adult Mont-Blanc Unlimited (2025/26)',
        description:
          'Every valley area — Brévent–Flégère, Grands Montets, Le Tour/Balme, Les Houches — plus the Aiguille du Midi and Montenvers, and days in Courmayeur (Italy) and Verbier (Switzerland).',
        price: 480,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.10,
        url: 'https://www.montblancnaturalresort.com/en/ticketing/montblanc-unlimited',
        contact: 'Chamonix Tourist Office +33 4 50 53 00 24 · Compagnie du Mont-Blanc',
        note: '2025/26 6-day adult; single day ~€100. Early-bird online booking ~25% off. Ski lifts carry 10% French VAT. Roughly flat into 2026/27.',
      },
      {
        id: 'pass-lepass',
        name: '6-day adult Chamonix Le Pass (2025/26)',
        description:
          'Valley ski lifts only (no Aiguille du Midi, Courmayeur or Verbier) — the value pass for skiers staying on the pistes across the four ski areas.',
        price: 360,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.10,
        url: 'https://www.seechamonix.com/ski-passes/about-chamonix-ski-pass-prices-39960',
        contact: 'Chamonix Tourist Office +33 4 50 53 00 24',
        note: '2025/26 6-day adult; single day €74. Family discounts for additional children.',
      },
    ],
  },
  {
    id: 'rental',
    label: 'Ski / snowboard rental — 6 days',
    icon: '🏂',
    defaultEnabled: false,
    defaultOptionId: 'rental-sport2000',
    unitHint: 'Skis + boots + helmet',
    options: [
      {
        id: 'rental-sport2000',
        name: 'Sport 2000 "Sport" mid pack',
        tier: 'Mid',
        description:
          'Mid-range (4★) skis + boots fitted at the La Ginabelle shop; clear tier pricing and online booking discounts.',
        price: 197,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.20,
        url: 'https://www.sport2000rent.com/en/skirental/destinations/france/haute-savoie/chamonix',
        contact: '+33 4 50 34 24 98',
        note: 'Tiers: Discovery €162 / Sport €197 / Performance €233 / Premium €269 (rack). Rental carries 20% French VAT.',
      },
      {
        id: 'rental-skiset',
        name: 'Skiset economy pack',
        tier: 'Budget',
        description:
          'Entry/mid pack from the biggest rental network in the Alps, multiple valley outlets; up to ~45% off booking online in advance.',
        price: 175,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.20,
        url: 'https://www.skiset.co.uk/ski-resort/chamonix',
        contact: '+33 4 50 93 56 73',
        note: '~€174.60 rack 6-day adult; ~€96 booked online. Engine-priced.',
      },
      {
        id: 'rental-intersport',
        name: 'Intersport adult pack',
        tier: 'Budget',
        description:
          '5 valley stores including Argentière (400 m from the Grands Montets lift); 6-day rentals with online discounts.',
        price: 195,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0.20,
        url: 'https://www.intersport-chamonix.com/en/',
        contact: '+33 4 50 47 73 50',
        note: 'Rack estimate ~€180–210; online booking cheaper. Engine-priced.',
      },
    ],
  },
  {
    id: 'insurance',
    label: 'Insurance',
    icon: '🛡️',
    defaultEnabled: true,
    defaultOptionId: 'ins-us-policy',
    unitHint: 'Medical + cancellation + piste rescue',
    options: [
      ...US_INSURANCE,
      {
        id: 'ins-carre-neige',
        name: 'Carré Neige (piste rescue) — 7 days',
        description:
          'French resort insurance sold with the lift pass: piste rescue & helicopter with no upfront payment, medical top-up, repatriation, unused-pass refund. €50,000 limit, max €50 excess.',
        price: 24.5,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://carreneige.com/en/nos-offres/carre-neige/',
        note: '€3.50/day, bought at lift-pass checkout. Insurance-premium tax included; VAT-exempt.',
      },
    ],
  },
  {
    id: 'skischool',
    label: 'Ski school (optional)',
    icon: '🎓',
    defaultEnabled: false,
    defaultOptionId: 'esf-group',
    unitHint: 'English-speaking instructors',
    options: [
      {
        id: 'esf-group',
        name: 'ESF adult group course — 6 half-days',
        description:
          '"Altitude" adult group course, 6 half-day sessions meeting at the Maison de la Montagne, Place de l’Église.',
        price: 350,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.ski-school-chamonix.co.uk/',
        contact: '+33 4 50 53 22 57',
        note: '5 half-days €295 / 6 half-days €350 (2025/26). ESF tuition is VAT-exempt (sports education).',
      },
      {
        id: 'esf-private',
        name: 'ESF private instructor — half day',
        tier: 'Premium',
        description:
          'Private instructor for your group per half-day engagement (1–3 people), 3 hours; lift pass not included.',
        price: 235,
        currency: 'EUR',
        unit: 'per_group',
        vatRate: 0,
        url: 'https://www.ski-school-chamonix.co.uk/',
        contact: '+33 4 50 53 22 57',
        note: '3 h (1–3 people) €235; 4 h €295 (2025/26).',
      },
      {
        id: 'evolution2-group',
        name: 'Evolution 2 group course — multi-day',
        tier: 'Mid',
        description:
          'Independent English-speaking school with small adult groups across the valley areas; multi-day morning courses.',
        price: 200,
        currency: 'EUR',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.evolution2.com/en/chamonix/',
        contact: 'planning.chamonix@evolution2.com · +33 4 50 55 53 57',
        note: 'Adult multi-day group from ~€200; private half-day from ~€215. Confirm the exact package in the engine.',
      },
    ],
  },
];

const logistics = [
  {
    step: 'T-6 to T-4 months — lock the frame',
    detail:
      'Fix a Saturday-to-Saturday week — valley hotels and ESF course starts run on the changeover. Note Chamonix is several separate ski areas (Grands Montets, Brévent–Flégère, Le Tour/Balme, Les Houches), not one linked domain, and the town sits low at ~1,035 m: book high-area access (Mont-Blanc Unlimited) for snow-sure skiing. Hold GVA flights (nonstops from SWISS/United/Delta; 1-stop fares bottom out ~2–3 months ahead). Request the hotel allotment: standard French Alps group terms are a 30% deposit on confirmation, balance ~30 days before arrival.',
  },
  {
    step: 'T-3 months — passes & transfer',
    detail:
      'Lifts are run by Compagnie du Mont-Blanc: buy Mont-Blanc Unlimited or Chamonix Le Pass at montblancnaturalresort.com (early-bird online ~25% off) or arrange a group manifest via the Chamonix Tourist Office (+33 4 50 53 00 24). Book the short Geneva transfer — Mountain Drop-offs shared shuttles, a Chamonix Valley Transfers private van matched to flight times, or the FlixBus/easyBus coach.',
  },
  {
    step: 'T-1 month — paper & money',
    detail:
      'Collect the final rooming list and rental sizes. Issue insurance (US policy per traveler + Carré Neige added to each pass at €3.50/day). Pay the hotel balance. Send suppliers flight numbers for transfer pickup; confirm ESF or Evolution 2 course groups and languages. Pick up the free Carte d’Hôte guest card at check-in for free valley bus and Mont-Blanc Express travel.',
  },
  {
    step: 'Trip week — run of show',
    detail:
      'Overnight flight Fri → Sat morning GVA arrival → shuttle or van up (~1 h 15) → check-in, passes at the desk, rental fitting → ski Sun–Fri (courses start Sunday; ride the free valley bus between areas) → Sat morning transfer down, afternoon flight home. Keep ≥3 h between GVA landing and the transfer cutoff.',
  },
  {
    step: 'Taxes & compliance',
    detail:
      'Taxe de séjour (Communauté de communes de la Vallée de Chamonix-Mont-Blanc) is charged per adult per night on top of room rates — confirm the season grid with the authority (valleedechamonix.taxesejour.fr; under-18s exempt). French VAT in these prices: hotels, half-board, transfers and lifts 10%; equipment rental 20%; ESF tuition and insurance exempt; international flights zero-rated. Selling packaged trips to US consumers may require Seller of Travel registration (CA/FL/WA/HI).',
  },
];

const CHAMONIX_SNOW: SnowMonth[] = [
  { month: 'Nov', snowfall: 50, base: 16, top: 35 },
  { month: 'Dec', snowfall: 65, base: 33, top: 123 },
  { month: 'Jan', snowfall: 138, base: 28, top: 214 },
  { month: 'Feb', snowfall: 130, base: 36, top: 341 },
  { month: 'Mar', snowfall: 98, base: 29, top: 379 },
  { month: 'Apr', snowfall: 70, base: 45, top: 350 },
];

export const chamonix: Resort = {
  id: 'chamonix',
  name: 'Chamonix-Mont-Blanc',
  country: 'France',
  flag: '\u{1F1EB}\u{1F1F7}',
  area: 'Vallée de Chamonix-Mont-Blanc',
  blurb:
    'The legendary mountaineering capital at the foot of Mont Blanc — extreme off-piste, glacier descents and dramatic high-altitude skiing across several separate ski areas.',
  lat: 45.9237,
  lon: 6.8694,
  elevationM: 1035,
  currency: 'EUR',
  gatewayAirports: ['GVA', 'LYS', 'GNB'],
  defaultOrigin: 'JFK',
  mapsName: 'Chamonix-Mont-Blanc',
  saturdayChangeover: true,
  season: { open: '2026-12-19', close: '2027-05-02', linkOpen: '2026-11-21', linkClose: '2027-05-02' },
  weeks: alpineWeeks,
  snowByMonth: CHAMONIX_SNOW,
  snowFacts:
    'Valley town sits low at ~1,035 m so town-level snow is unreliable, but lift-served terrain rises to ~3,300 m at Grands Montets — high areas hold 300+ cm top depth in Feb/Mar. ~517 cm average annual snowfall, ~40 snow days.',
  components,
  logistics,
};

export default chamonix;
