// St. Moritz, Switzerland — Engadin (Corviglia / Corvatsch). Shaped like
// val-thorens.ts (see resorts/types.ts for the schema; resorts/shared.ts for
// US_INSURANCE). Swiss lodging VAT special rate 3.8%, standard rate 8.1%.
// 2026/27 where published, else verified 2025/26.

import type { Resort, SnowMonth } from './types';
import type { TripComponent } from '../tripBuilderData';
import { alpineWeeks } from '../seasonData';
import { US_INSURANCE } from './shared';

const components: TripComponent[] = [
  {
    id: 'flights',
    label: 'Getting there',
    icon: '✈️',
    defaultEnabled: true,
    defaultOptionId: 'flight-zrh',
    unitHint: 'Round trip per traveler — mixable per person',
    options: [
      {
        id: 'flight-zrh',
        name: 'JFK → Zurich (SWISS / Delta / United)',
        tier: 'Budget',
        description:
          'JFK → ZRH, mostly nonstop (~8 h), then the scenic rail via Chur into the Engadin. Zurich is the preferred gateway for St. Moritz.',
        price: 820,
        currency: 'USD',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.google.com/travel/flights/flights-from-new-york-to-zurich.html',
        note: 'Estimated winter band $650–$1,150 round trip; peak holiday weeks 30–60% higher. International air is VAT-exempt.',
      },
      {
        id: 'flight-ewr',
        name: 'EWR → Zurich nonstop (United)',
        tier: 'Premium',
        description: 'Newark → ZRH daily United nonstop — the comfortable Saturday-changeover choice.',
        price: 900,
        currency: 'USD',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.kayak.com/flight-routes/Newark-EWR/Zurich-ZRH',
        note: 'Estimated $600–$1,100 round trip winter; peak higher.',
      },
      {
        id: 'flight-bos',
        name: 'BOS → Zurich (SWISS seasonal nonstop / 1-stop)',
        tier: 'Budget',
        description: 'Boston → ZRH on SWISS seasonal nonstop or 1-stop connections.',
        price: 880,
        currency: 'USD',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.momondo.com/flights/boston/zurich',
        note: 'Estimated $650–$1,200 round trip winter.',
      },
      {
        id: 'flight-gva',
        name: 'JFK → Geneva (1-stop)',
        tier: 'Budget',
        description:
          'JFK → GVA via a European hub for travelers who prefer Geneva; the Engadin is ~4.5–5 h onward, so Zurich is usually better.',
        price: 800,
        currency: 'USD',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.google.com/travel/flights/flights-from-new-york-to-geneva.html',
        note: 'Estimated $650–$1,100 round trip, 1-stop. Longer onward transfer than from Zurich.',
      },
    ],
  },
  {
    id: 'hotel',
    label: 'Accommodation — 7 nights',
    icon: '🏨',
    defaultEnabled: true,
    defaultOptionId: 'hotel-hauser',
    unitHint: 'Breakfast unless noted',
    options: [
      {
        id: 'hotel-youthhostel',
        lat: 46.4892918,
        lon: 9.8462174,
        name: 'Youth Hostel St. Moritz',
        tier: 'Hostel',
        description:
          'Lakeside hostel in St. Moritz-Bad with dorm beds and simple private rooms, breakfast included — the entry-level base in a prestige resort.',
        price: 68,
        currency: 'CHF',
        unit: 'per_person_night',
        vatRate: 0.038,
        url: 'https://www.youthhostel.ch/en/hostels/st-moritz',
        contact: 'st.moritz@youthhostel.ch · +41 81 836 61 11',
        imageUrl:
          'https://backend.youthhostel.ch/sites/default/files/styles/header/public/canto/r1f8lvpesh3nbcr04vurc3r73d/20240403_Jugendherberge-St-Moritz-Sommer-Aussenansicht-Michel_van_Grondel-04.jpg.webp',
        note: 'Estimated CHF 55–80 pp/night dorm incl. breakfast; private double ~CHF 150–210/room/night.',
      },
      {
        id: 'hotel-laudinella',
        lat: 46.4859092,
        lon: 9.8373648,
        name: 'Hotel Laudinella ★★★',
        tier: 'Mid',
        description:
          'Recently renovated, culturally minded good-value hotel in St. Moritz-Bad with a rooftop spa, three restaurants and two bars.',
        price: 220,
        currency: 'CHF',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.038,
        url: 'https://www.laudinella.ch/en/',
        contact: 'info@laudinella.ch · +41 81 836 00 00',
        imageUrl: 'https://www.laudinella.ch/wp-content/uploads/2022/05/Laudinella_Lakeview.jpg',
        note: 'Estimated CHF 150–290/room/night incl. breakfast.',
      },
      {
        id: 'hotel-hauser',
        lat: 46.4974602,
        lon: 9.8378897,
        name: 'Hotel Hauser ★★★',
        tier: 'Mid',
        description:
          'Fourth-generation family-run hotel (since 1892) in central St. Moritz-Dorf, famous for its confiserie and Engadin nut torte; balcony rooms.',
        price: 275,
        currency: 'CHF',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.038,
        url: 'https://www.hotelhauser.ch/en/',
        contact: 'relax@hotelhauser.ch · +41 81 837 50 50',
        imageUrl:
          'https://hotelhauser.ch/wp-content/uploads/resized/2022/09/LargeRoomBalconyLaerche-1200x0-c-default.jpg',
        note: 'Estimated CHF 210–340/room/night incl. breakfast.',
      },
      {
        id: 'hotel-schweizerhof',
        lat: 46.4968432,
        lon: 9.8380558,
        name: 'Hotel Schweizerhof ★★★★S',
        tier: 'Premium',
        description:
          'Central 82-room hotel on Via dal Bagn with mountain and lake views, a wellness area and lively bars and restaurants.',
        price: 420,
        currency: 'CHF',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.038,
        url: 'https://www.schweizerhofstmoritz.ch/en/',
        contact: 'info@schweizerhofstmoritz.ch · +41 81 837 07 07',
        imageUrl:
          'https://schweizerhofstmoritz.ch/wp-content/uploads/2018/12/Hotel-Schweizerhof-St.Moritz-Junior-Suite-Corvatsch-Seeblick.jpg',
        note: 'Estimated CHF 320–560/room/night, or ~CHF 180–260 pp/night half-board.',
      },
      {
        id: 'hotel-kulm',
        lat: 46.4990142,
        lon: 9.8386914,
        name: 'Kulm Hotel St. Moritz ★★★★★S',
        tier: 'Luxury',
        description:
          'The birthplace of Alpine winter tourism (est. 1856) — a grand resort hotel above the lake with its own park, ice rink and spa, beside the Corviglia funicular.',
        price: 850,
        currency: 'CHF',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.038,
        url: 'https://www.kulm.com/en/',
        contact: 'info@kulm.com · +41 81 836 80 00',
        imageUrl:
          'https://media.kulm.com/size:w800,mode:crop/wp-content/uploads/sites/4/2025/04/08123052/Medium-Exterior-15-scaled.jpg',
        note: 'Estimated CHF 750–1,600/room/night, typically half-board; higher over festive/peak weeks.',
      },
      {
        id: 'hotel-badrutts',
        lat: 46.497,
        lon: 9.841,
        name: "Badrutt's Palace Hotel ★★★★★S",
        tier: 'Prestige',
        description:
          "St. Moritz's landmark castle-like grand hotel (since 1896) overlooking the lake — a world-famous high-society address (Forbes 5-Star, World's 50 Best Hotels).",
        price: 1400,
        currency: 'CHF',
        unit: 'per_room_night',
        capacity: 2,
        vatRate: 0.038,
        url: 'https://badruttspalace.com/en/',
        contact: 'reservations@badruttspalace.com · +41 81 837 10 00',
        imageUrl: 'https://badruttspalace.com/media/ja1heqpd/badrutts-palace-rooms.jpg',
        note: 'Estimated CHF 1,300–3,500+/room/night; far higher over Christmas/New Year.',
      },
    ],
  },
  {
    id: 'transfer',
    label: 'Airport transfer ZRH ⇄ St. Moritz',
    icon: '🚐',
    defaultEnabled: true,
    defaultOptionId: 'transfer-train',
    unitHint: '~200 km, ~3–3.5 h each way',
    options: [
      {
        id: 'transfer-train',
        name: 'Train — SBB + Rhaetian Railway via Chur',
        tier: 'Budget',
        description:
          'Zurich Airport → Zurich HB → Chur (SBB), then RhB over the UNESCO Albula line to St. Moritz. One change at Chur, roughly hourly, ~3h20–3h40 from Zurich HB.',
        price: 180,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0.081,
        url: 'https://www.rhb.ch/en',
        contact: 'SBB +41 848 44 66 88 · RhB +41 81 288 65 65',
        note: 'Estimated ~CHF 88–91 one-way from the airport → ~CHF 180 return 2nd class; Half-Fare / Swiss Travel Pass reduce this substantially.',
      },
      {
        id: 'transfer-glacierexpress',
        name: 'Glacier Express panoramic (scenic add-on)',
        tier: 'Premium',
        description:
          'The famous panoramic train — best as a scenic arrival or day trip rather than the fastest connector; the St. Moritz–Chur segment plus a mandatory seat reservation.',
        price: 213,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0.081,
        url: 'https://www.glacierexpress.ch/en',
        contact: 'Booking via shop.glacierexpress.ch',
        note: 'Confirmed: 2nd class up to CHF 159 + CHF 54 mandatory reservation = CHF 213 (full Zermatt–St. Moritz route); the Chur segment alone is cheaper.',
      },
      {
        id: 'transfer-shared-van',
        name: 'Shared shuttle van (seat-in-van)',
        tier: 'Budget',
        description:
          'Seat-in-van transfer Zurich Airport → St. Moritz for travelers who prefer door-to-door over the rail change at Chur. Confirm operator and timings when booking.',
        price: 300,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0.081,
        url: 'https://www.stmoritz.com',
        contact: 'Licensed transfer providers listed by St. Moritz Tourism',
        note: 'Estimated ~CHF 120–190 pp one-way → ~CHF 220–350 return; the train is usually the more robust shared option.',
      },
      {
        id: 'transfer-private-van',
        name: 'Private transfer van (1–8 pax)',
        tier: 'Premium',
        description:
          'Door-to-door private car or minivan Zurich Airport → St. Moritz, ~2h45–3h15; competitive for groups of 4–8.',
        price: 2000,
        currency: 'CHF',
        unit: 'per_vehicle_return',
        capacity: 8,
        vatRate: 0.081,
        url: 'https://www.stmoritz.com',
        contact: 'Licensed limousine/taxi providers via St. Moritz Tourism',
        note: 'Estimated CHF 950–1,350/minivan one-way → ~CHF 2,000 return planning figure.',
      },
    ],
  },
  {
    id: 'skipass',
    label: 'Ski pass — 6 days Engadin St. Moritz',
    icon: '🎿',
    defaultEnabled: true,
    defaultOptionId: 'pass-allmountain',
    unitHint: '~350 km across Corviglia, Corvatsch & Diavolezza',
    options: [
      {
        id: 'pass-allmountain',
        name: '6-day adult all-mountain pass',
        description:
          'Covers the whole Engadin St. Moritz pool — Corviglia/Piz Nair, Corvatsch/Furtschellas and Diavolezza/Lagalb, up to 3,303 m on Corvatsch.',
        price: 376,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0.081,
        url: 'https://www.mountains.ch/en/tickets/',
        contact: 'Engadin St. Moritz Mountains +41 81 830 00 00 · info@mountains.ch',
        imageUrl:
          'https://www.mountains.ch/fileadmin/user_upload/corviglia-winter-skiing.jpg',
        note: 'Verified 2025/26 6-day adult all-mountain CHF 376 (2026/27 not yet published). Day passes are dynamic (CHF 11–76). Swiss lift tickets carry 8.1% VAT.',
      },
      {
        id: 'pass-corvatsch-day',
        name: 'Corvatsch single-mountain day pass',
        description:
          'Single-mountain option for the long, high Corvatsch/Furtschellas sector (season into late April) — for travelers who want to ski one area or add a day.',
        price: 76,
        currency: 'CHF',
        unit: 'per_person_day',
        vatRate: 0.081,
        url: 'https://www.corvatsch-diavolezza.ch/en/',
        contact: 'Corvatsch AG +41 81 838 73 73 · info@corvatsch.ch',
        note: 'Dynamic adult day pricing to ~CHF 76; cheaper booked early online.',
      },
    ],
  },
  {
    id: 'rental',
    label: 'Ski / snowboard rental — 6 days',
    icon: '🏂',
    defaultEnabled: false,
    defaultOptionId: 'rental-skiservice',
    unitHint: 'Skis + boots + helmet',
    options: [
      {
        id: 'rental-skiservice',
        name: 'Skiservice Corvatsch mid pack',
        tier: 'Mid',
        description:
          '16-shop Engadin network (incl. "Playground by Skiservice" in St. Moritz); 6-day mid-range skis + boots + helmet.',
        price: 340,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0.081,
        url: 'https://www.skiservice-corvatsch.com/en/',
        contact: '+41 81 838 77 77',
        note: 'Estimated CHF 300–420 for a 6-day mid pack.',
      },
      {
        id: 'rental-suvretta',
        name: 'Suvretta Sports pack',
        tier: 'Premium',
        description: 'Established St. Moritz shop; 6-day performance-leaning adult package.',
        price: 360,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0.081,
        url: 'https://www.suvretta-sports.ch/en/',
        contact: '+41 81 833 62 33',
        note: 'Estimated CHF 320–440 for a 6-day pack.',
      },
      {
        id: 'rental-intersport',
        name: 'Intersport Rent mid pack',
        tier: 'Budget',
        description: 'Intersport St. Moritz outlets; 6-day mid-range adult pack, value end.',
        price: 300,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0.081,
        url: 'https://www.intersportrent.ch',
        note: 'Estimated CHF 260–380 for a 6-day mid pack — engine-priced.',
      },
    ],
  },
  {
    id: 'insurance',
    label: 'Insurance',
    icon: '🛡️',
    defaultEnabled: true,
    defaultOptionId: 'ins-us-policy',
    unitHint: 'Medical + cancellation + mountain rescue',
    options: [
      ...US_INSURANCE,
      {
        id: 'ins-rega',
        name: 'REGA patronage (Swiss Air-Rescue) — 1 year',
        tier: 'Add-on',
        description:
          'Swiss Air-Rescue patronage: Rega may waive helicopter rescue-mission costs for patrons when insurance does not cover them. A donation/goodwill scheme, not insurance — pair it with a travel-medical policy.',
        price: 40,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.rega.ch/en/become-a-patron',
        contact: 'Rega (from abroad) +41 44 654 32 22',
        note: 'CHF 40/adult/year; partnership/family tier ~CHF 80. Switzerland has no Carré Neige equivalent.',
      },
    ],
  },
  {
    id: 'skischool',
    label: 'Ski school (optional)',
    icon: '🎓',
    defaultEnabled: false,
    defaultOptionId: 'sss-group',
    unitHint: 'English-speaking instructors',
    options: [
      {
        id: 'sss-group',
        name: 'Swiss Ski & Snowboard School St. Moritz — 6-day group',
        description:
          'Adult group course over consecutive mornings, meeting at Via Stredas near the Corviglia funicular.',
        price: 420,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.skischool.ch/en/',
        contact: 'info@skischool.ch · +41 81 830 01 01',
        note: 'Estimated CHF 380–460 per 6-day week (~CHF 90–110/half-day). See price list on skischool.ch.',
      },
      {
        id: 'sss-private',
        name: 'Swiss Ski School private — half day',
        tier: 'Premium',
        description: 'Private instructor ~3 h for your group; lift pass not included.',
        price: 420,
        currency: 'CHF',
        unit: 'per_group',
        vatRate: 0,
        url: 'https://www.skischool.ch/en/info-faqs/price-list',
        contact: 'info@skischool.ch · +41 81 830 01 01',
        note: 'Estimated CHF 380–460 for a half-day private.',
      },
      {
        id: 'ssscp-group',
        name: 'Snowsport School Corvatsch–Pontresina — group week',
        tier: 'Mid',
        description:
          'Serves the Corvatsch side (Silvaplana-Surlej, Sils, Maloja); adult group course by the week.',
        price: 390,
        currency: 'CHF',
        unit: 'per_person',
        vatRate: 0,
        url: 'https://www.ssscp.ch/',
        contact: 'info@ssscp.ch · +41 81 544 0 544',
        note: 'Estimated CHF 350–430/week; private half-day ~CHF 350–440.',
      },
    ],
  },
];

const logistics = [
  {
    step: 'T-6 to T-4 months — lock the frame',
    detail:
      'Fix a Saturday-to-Saturday week (Alpine changeover). Hold Zurich flights early — ZRH is the practical gateway (direct rail via Chur). Request the hotel allotment: standard Swiss group terms are a deposit on confirmation and the balance ~30 days before arrival; negotiate the release date (60–90 days pre-arrival). St. Moritz peaks hard over festive weeks and Presidents/school breaks.',
  },
  {
    step: 'T-3 months — passes & transfer',
    detail:
      'Buy 6-day all-mountain Engadin passes on mountains.ch (Corviglia/Corvatsch/Diavolezza pool); day passes are dynamic so early online booking is cheaper. Decide arrival: SBB + Rhaetian Railway via Chur (robust and scenic), a shared seat-in-van, or a private minivan for groups of 4–8. Reserve any Glacier Express segment (mandatory seat reservation).',
  },
  {
    step: 'T-1 month — paper & money',
    detail:
      'Collect the final rooming list and rental sizes (Skiservice Corvatsch / Suvretta / Intersport). Issue insurance (US policy per traveler; optional Rega patronage at CHF 40/adult/year — goodwill, not insurance). Pay the hotel balance. Confirm rail connections at Chur; book Swiss Ski School course groups and languages.',
  },
  {
    step: 'Trip week — run of show',
    detail:
      'Fly to ZRH → train via Chur on the Rhaetian Railway (~3.5 h, one change) → arrive St. Moritz → check-in, collect passes, rental fitting → ski Sun–Fri across Corviglia and Corvatsch (long high seasons, plentiful Engadin sun) → Sat train back to the airport. Allow margin for the Chur connection with luggage and skis.',
  },
  {
    step: 'Taxes & compliance',
    detail:
      'Swiss VAT in these prices: accommodation at the special 3.8% lodging rate; lift passes, transfers, rail, rental and most services at the 8.1% standard rate; ski tuition and insurance exempt; international flights zero-rated. A guest/visitor tax is charged per person per night on top of room rates — confirm with St. Moritz Tourism. Selling packaged trips to US consumers may require Seller of Travel registration (CA/FL/WA/HI).',
  },
];

const ST_MORITZ_SNOW: SnowMonth[] = [
  { month: 'Nov', snowfall: 38, base: 22, top: 55 },
  { month: 'Dec', snowfall: 52, base: 50, top: 90 },
  { month: 'Jan', snowfall: 48, base: 68, top: 130 },
  { month: 'Feb', snowfall: 48, base: 75, top: 160 },
  { month: 'Mar', snowfall: 52, base: 75, top: 180 },
  { month: 'Apr', snowfall: 33, base: 33, top: 170 },
];

export const stMoritz: Resort = {
  id: 'st-moritz',
  name: 'St. Moritz',
  country: 'Switzerland',
  flag: '🇨🇭',
  area: 'Engadin',
  blurb:
    'The birthplace of Alpine winter tourism at 1,822 m — a sun-drenched, prestige Engadin resort spread across Corviglia, Corvatsch and the Diavolezza glacier.',
  lat: 46.4908,
  lon: 9.8355,
  elevationM: 1822,
  currency: 'CHF',
  gatewayAirports: ['ZRH', 'GVA'],
  defaultOrigin: 'JFK',
  mapsName: 'St. Moritz',
  saturdayChangeover: true,
  season: { open: '2026-11-21', close: '2027-05-02', linkOpen: '2026-11-21', linkClose: '2027-05-02' },
  weeks: alpineWeeks,
  snowByMonth: ST_MORITZ_SNOW,
  snowFacts:
    'High, dry Engadin valley at 1,822 m with skiing to 3,303 m on Corvatsch and a long glacier season on Diavolezza. ~350 cm average annual snowfall and exceptional sunshine — snow-sure into early May.',
  components,
  logistics,
};

export default stMoritz;
